{
 "title": "ETH",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Block Interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "poller_block_interval" }
   ]
  },
  {
   "title": "Transaction Interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "poller_transaction_interval" }
   ]
  },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "poller_tracking_events_agent1" }
   ]
  },
  {
   "title": "Block transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_block_transactions" }
   ]
  },
  {
   "title": "Block gas",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_block_gas" }
   ]
  },
  {
   "title": "Block size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_block_size" }
   ]
  },
  {
   "title": "Gas Price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_gas_price" }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "eth_hashrate" }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "targets": [
    { "expr": "parity_node_peers" }
   ]
  },
  {
   "title": "Sync",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "targets": [
    { "expr": "eth_syncing" }
   ]
  },
  {
   "title": "Pending",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "parity_pendingTransactions" }
   ]
  },
  {
   "title": "Fork",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "poller_fork" }
   ]
  },
  {
   "title": "Block number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 12 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "eth_block_info" }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 12 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "parity_node_info" }
   ]
  },
  {
   "title": "Chain name",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "parity_node_info" }
   ]
  }
 ]
}