{
 "title": "HLF",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Network Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Transactions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ledger_transaction_count{channel=\"mychannel\",chaincode=\"mycc:1\"}"
    }
   ]
  },
  {
   "title": "Transactions Frequency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ledger_transaction_count{channel=\"mychannel\",chaincode=\"mycc:1\"}[1m])"
    }
   ]
  },
  {
   "title": "# Blocks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ledger_blockchain_height{channel=\"mychannel\"}"
    }
   ]
  },
  {
   "title": "Block Frequency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ledger_blockchain_height{channel=\"mychannel\", instance=\"peer0.org1.bnc.com:9443\"}[1m])"
    }
   ]
  },
  { "title": "Network Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fabric Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "fabric_version" }
   ]
  },
  {
   "title": "Committed blocks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "consensus_etcdraft_committed_block_number{channel=\"mychannel\"}"
    }
   ]
  },
  {
   "title": "Endorsment Proposal Successfull",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "endorser_successful_proposals" }
   ]
  },
  {
   "title": "Endorsment Proposal Failure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "endorser_proposals_received - endorser_successful_proposals"
    }
   ]
  },
  {
   "title": "Peers known",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "gossip_membership_total_peers_known"
    }
   ]
  },
  {
   "title": "Endorser proposal duration (avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "endorser_proposal_duration_sum{channel=\"mychannel\", chaincode=\"mycc\"} / endorser_proposal_duration_count{channel=\"mychannel\", chaincode=\"mycc\"}"
    }
   ]
  },
  {
   "title": "Orderers raft",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "consensus_etcdraft_active_nodes"
    }
   ]
  },
  {
   "title": "Validation duration (avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "broadcast_enqueue_duration_sum{channel=\"mychannel\"}/ broadcast_enqueue_duration_count{channel=\"mychannel\"}"
    }
   ]
  }
 ]
}